### PR TITLE
Updated to debian stretch and added ffmpeg in build

### PR DESCRIPTION
**Pull request by davebv**
It would be good to have it in the build to save boot time in case of using ffmpeg npm homebridge.

### CODE REVIEW

**Review by nicx — APPROVED** [review]

**Review by nicx — APPROVED** [review]
working as expected

**Comment by davebv** [comment]
Great!

**Comment by marcoraddatz** [comment]
Thanks for the PR. What do you think of putting ffmpeg into a separate branch?

**Comment by nicx** [comment]
I dont matter ffmpeg. my wish is still only the stable branch of debian strech instead the outdated jessie.

**Comment by davebv** [comment]
I would rather include ffmpeg by default, since it heps a lot booting and size increase is not too much.

**Comment by marcoraddatz** [comment]
Thanks for the PR!

**Comment by davebv** [comment]
thanks for merging!

**Pull request merged**
